/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testPK;

import java.awt.Color;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Gic
 */
public class ftest extends javax.swing.JFrame {

    /**
     * Creates new form ftest
     */
    public ftest() throws InterruptedException {
        initComponents();
        //JFrame jf = new JFrame("test");
        //jf.setSize(800, 600);
        this.setSize(800,600);
        JPanel jp = new JPanel();
        jp.setSize(800, 600);
        jp.setBackground(Color.red);
        JLabel jl = new JLabel("hello world!");
        jp.setLayout(null);
        Dimension size = jl.getPreferredSize();
        int x = 0;
        boolean reverse = false;
        jl.setBounds(x, jp.getHeight() / 2, size.width, size.height);
        jp.add(jl);
        this.add(jp);
        this.setVisible(true);
        jl.setBounds(20, jp.getHeight()/2, size.width, size.height);
        Thread.sleep(10);
        jl.setBounds(50, jp.getHeight()/2, size.width, size.height);
        Thread.sleep(10);
        jl.setBounds(100, jp.getHeight()/2, size.width, size.height);
//        while(true){
//            if(x==jp.getWidth()-60&&!reverse) 
//                reverse=true;
//            else if(x==0&&reverse)
//                reverse=false;
//            if(reverse)
//                x--;
//            else x++;
//            jl.setBounds(x,jp.getHeight()/2, size.width, size.height);
//            Thread.sleep(10);
//        }

//        for (int i = 0; i < 20; i++) {
//            if (i % 2 == 0) {
//                for (int j = 50; j > 0; j-=10) {
//                    jl.setBounds(j, jp.getHeight() / 2, size.width, size.height);
//                    Thread.sleep(10);
//                }
//            } else {
//                for (int j = 0; j < 50; j+=10) {
//                    jl.setBounds(j, jp.getHeight() / 2, size.width, size.height);
//                    Thread.sleep(10);
//                }
//            }
//
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ftest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ftest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ftest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ftest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ftest().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ftest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
