/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testPK;

import BLL.MY_HANDLE;
import DAL.MY_HANDLE_CONNECTION;
import DTO.Sach;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import testPK.img.flag;
/**
 *
 * @author Magic
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    private final MY_HANDLE_CONNECTION db = new MY_HANDLE_CONNECTION();
    private final MY_HANDLE XULY = new MY_HANDLE();
    flag fl = new flag();

    public test() throws IOException, SQLException {
        initComponents();
        LoadPanelSach();

    }

    private void LoadPanelSach() {
        LayBangSach("Select * from Sach");

    }

    private void LayBangSach(String query) {
        DefaultTableModel model = (DefaultTableModel) tableDSS.getModel();
        model.setRowCount(0);
        String MaSach, TenSach, SoLuong, MaTheLoai, TomTat, TacGia;

        try {
            ResultSet rs = db.RunQuery(query);
            while (rs.next()) {
                MaSach = rs.getString(1);
                TenSach = rs.getString(2);
                SoLuong = rs.getString(3);
                MaTheLoai = rs.getString(4);
                TomTat = rs.getString(5);
                TacGia = rs.getString(6);
                Sach sach = new Sach(MaSach, TenSach, SoLuong, MaTheLoai, TomTat, TacGia);
                model.addRow(sach.ToListString());

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Co loi khi lay du lieu Sach:\n" + ex.getMessage());
        }
    }

    private int CHỌNSÁCH = -1;

    private void ChọnDòngSách() throws IOException {
        CHỌNSÁCH = tableDSS.getSelectedRow();
        lbMaSach.setText(tableDSS.getValueAt(CHỌNSÁCH, 0).toString());
        lbTenSach.setText(tableDSS.getValueAt(CHỌNSÁCH, 1).toString());
        //tbSoluong.setText(tableDSS.getValueAt(CHỌNSÁCH, 2).toString());
        //tbTomTat.setText(tableDSS.getValueAt(CHỌNSÁCH, 4).toString());
        lbTacGia.setText(tableDSS.getValueAt(CHỌNSÁCH, 5).toString());
        //cbbTheLoai.setSelectedItem(MAPTHELOAI.get(Integer.parseInt(tableDSS.getValueAt(CHỌNSÁCH, 3).toString())));
        lbTheLoai.setText(tableDSS.getValueAt(CHỌNSÁCH, 3).toString());

        String imgname = tableDSS.getValueAt(CHỌNSÁCH, 0).toString() + ".jpg";
        System.out.println(imgname);

        URL link2 = fl.getClass().getResource(imgname);
        BufferedImage myPicture = ImageIO.read(link2);
        Image dimg = myPicture.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        this.jLabel1.setIcon(new ImageIcon(dimg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tabpnSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDSS = new javax.swing.JTable();
        tbTImkiemSach = new javax.swing.JTextField();
        btTimKiemSach = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btChonFile = new javax.swing.JButton();
        lbTenSach = new javax.swing.JLabel();
        lbMaSach = new javax.swing.JLabel();
        lbTheLoai = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbTacGia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tabpnSach.setOpaque(false);

        tableDSS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng còn lại", "Thể loại", "Tóm tắt", "Tác giả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDSS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDSSMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableDSSMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableDSS);

        btTimKiemSach.setText("Search");
        btTimKiemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemSachActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        btXoa.setText("Xoa");
        btXoa.setMaximumSize(new java.awt.Dimension(72, 72));
        btXoa.setMinimumSize(new java.awt.Dimension(72, 72));
        btXoa.setName(""); // NOI18N
        btXoa.setPreferredSize(new java.awt.Dimension(72, 72));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btSua.setText("Sua");
        btSua.setMaximumSize(new java.awt.Dimension(72, 72));
        btSua.setMinimumSize(new java.awt.Dimension(72, 72));
        btSua.setName(""); // NOI18N
        btSua.setPreferredSize(new java.awt.Dimension(72, 72));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btChonFile.setText("Chon file");
        btChonFile.setMaximumSize(new java.awt.Dimension(72, 72));
        btChonFile.setMinimumSize(new java.awt.Dimension(72, 72));
        btChonFile.setName(""); // NOI18N
        btChonFile.setPreferredSize(new java.awt.Dimension(72, 72));
        btChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonFileActionPerformed(evt);
            }
        });

        lbTenSach.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lbTenSach.setText("Tên sách");

        lbMaSach.setText("ma");

        lbTheLoai.setText("theloait");

        jLabel1.setText("jLabel1");

        lbTacGia.setText("taacgia");

        javax.swing.GroupLayout tabpnSachLayout = new javax.swing.GroupLayout(tabpnSach);
        tabpnSach.setLayout(tabpnSachLayout);
        tabpnSachLayout.setHorizontalGroup(
            tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpnSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabpnSachLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btChonFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabpnSachLayout.createSequentialGroup()
                        .addComponent(tbTImkiemSach)
                        .addGap(33, 33, 33)
                        .addComponent(btTimKiemSach))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabpnSachLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabpnSachLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabpnSachLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        tabpnSachLayout.setVerticalGroup(
            tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpnSachLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabpnSachLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tabpnSachLayout.createSequentialGroup()
                        .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabpnSachLayout.createSequentialGroup()
                                .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btChonFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tabpnSachLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(lbTacGia)))
                                .addGap(18, 18, 18)
                                .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbTheLoai))
                        .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabpnSachLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabpnSachLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbMaSach)
                                .addGap(34, 34, 34)))))
                .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTImkiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTimKiemSach)
                    .addComponent(lbTenSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabpnSachLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 6, 6, 6);
        getContentPane().add(tabpnSach, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableDSSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDSSMouseClicked

    }//GEN-LAST:event_tableDSSMouseClicked

    private void btTimKiemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemSachActionPerformed

    }//GEN-LAST:event_btTimKiemSachActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed

    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed

    }//GEN-LAST:event_btSuaActionPerformed

    private void btChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonFileActionPerformed
        JFileChooser fc = new JFileChooser();
        if (fc.showDialog(this, "Chon") == 0) {
            File f=fc.getSelectedFile();
            BufferedImage myPicture;
            try {
                myPicture = ImageIO.read(f);
                Image dimg = myPicture.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
                this.jLabel1.setIcon(new ImageIcon(dimg));
                f.renameTo(new File("G:\\"+f.getName()));
                
            } catch (IOException ex) {
                Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

    }//GEN-LAST:event_btChonFileActionPerformed

    private void tableDSSMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDSSMouseReleased
        try {
            ChọnDòngSách();
        } catch (IOException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableDSSMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new test().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChonFile;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btTimKiemSach;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbMaSach;
    private javax.swing.JLabel lbTacGia;
    private javax.swing.JLabel lbTenSach;
    private javax.swing.JLabel lbTheLoai;
    private javax.swing.JTable tableDSS;
    private javax.swing.JPanel tabpnSach;
    private javax.swing.JTextField tbTImkiemSach;
    // End of variables declaration//GEN-END:variables
}
